FROM archlinux/archlinux:latest
RUN mkdir -p /workspace
RUN pacman -Syyu --noconfirm autoconf automake gcc git make patch pkgconf && rm -rf /var/cache/pacman/pkg/*
RUN pacman -Syyu --noconfirm bzip2 lzo xz libgcrypt zlib lz4 zstd && rm -rf /var/cache/pacman/pkg/*
RUN pacman -Syyu --noconfirm xfsprogs btrfs-progs e2fsprogs && rm -rf /var/cache/pacman/pkg/*
CMD ["/usr/bin/bash"]
WORKDIR /workspace
